name: Build Flutter APK

on:
  workflow_dispatch:
    inputs:
      zip_url:
        description: "URL ZIP Project Flutter"
        required: true
        type: string
      build_type:
        description: "debug atau release"
        required: true
        default: "debug"
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip wget

      - name: Download ZIP
        run: wget "${{ github.event.inputs.zip_url }}" -O project.zip

      - name: Extract ZIP
        run: unzip project.zip -d project

      - name: Find Flutter Project
        run: |
          DIR=$(find project -name pubspec.yaml | head -n 1)
          if [ -z "$DIR" ]; then
            echo "Project Flutter tidak ditemukan!"
            exit 1
          fi
          echo "PROJECT_DIR=$(dirname "$DIR")" >> $GITHUB_ENV

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Dependencies
        run: |
          cd "$PROJECT_DIR"
          flutter pub get

      - name: Build APK
        run: |
          cd "$PROJECT_DIR"
          if [ "${{ github.event.inputs.build_type }}" = "release" ]; then
            flutter build apk --release
          else
            flutter build apk --debug
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/*.apk
