name: Build APK

on:
  workflow_dispatch:
    inputs:
      zip_url:
        description: "URL ZIP Project Flutter"
        required: true
        type: string
      tag:
        description: "Tag Build"
        required: false
        default: "v1.0"
        type: string
      build_type:
        description: "debug atau release"
        required: true
        default: "debug"
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y unzip wget curl git

      - name: Download ZIP
        run: |
          wget "${{ github.event.inputs.zip_url }}" -O project.zip

      - name: Extract ZIP
        run: |
          unzip -q project.zip -d project

      - name: Find Flutter Project
        run: |
          PUBSPEC=$(find project -name pubspec.yaml | head -n 1)
          if [ -z "$PUBSPEC" ]; then
            echo "Project Flutter tidak ditemukan!"
            exit 1
          fi
          echo "PROJECT_DIR=$(dirname "$PUBSPEC")" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter Version
        run: flutter --version

      - name: Install Dependencies
        run: |
          cd "$PROJECT_DIR"
          flutter pub get

      - name: Build APK
        run: |
          cd "$PROJECT_DIR"
          if [ "${{ github.event.inputs.build_type }}" = "release" ]; then
            flutter build apk --release
          else
            flutter build apk --debug
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-${{ github.event.inputs.tag }}
          path: |
            ${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/*.apk
